/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_keda_firstjni_MyJniTest */

#ifndef _Included_com_keda_firstjni_MyJniTest
#define _Included_com_keda_firstjni_MyJniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_keda_firstjni_MyJniTest
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_keda_firstjni_MyJniTest_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
